foreground         #c1c2c4
background         #090b15
background_opacity 1.0
cursor             #c1c2c4

active_tab_foreground     #090b15
active_tab_background     #c1c2c4
inactive_tab_foreground   #c1c2c4
inactive_tab_background   #090b15

active_border_color   #c1c2c4
inactive_border_color #090b15
bell_border_color     #2F558E

color0       #090b15
color8       #585b6c
color1       #2F558E
color9       #2F558E
color2       #35609F
color10      #35609F
color3       #355FA0
color11      #355FA0
color4       #3967AC
color12      #3967AC
color5       #3B6BB3
color13      #3B6BB3
color6       #3D6EBA
color14      #3D6EBA
color7       #c1c2c4
color15      #c1c2c4
