--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/data/data/com.termux/files/home/storage/dcim/Restored/IMG-20240726-WA0001.jpg"

-- Special
background="#090b15"
foreground="#c1c2c4"
cursor="#c1c2c4"

-- Colors
color0="#090b15"
color1="#2F558E"
color2="#35609F"
color3="#355FA0"
color4="#3967AC"
color5="#3B6BB3"
color6="#3D6EBA"
color7="#c1c2c4"
color8="#585b6c"
color9="#2F558E"
color10="#35609F"
color11="#355FA0"
color12="#3967AC"
color13="#3B6BB3"
color14="#3D6EBA"
color15="#c1c2c4"
