colors:

  primary:
    background: "#090b15"
    foreground: "#c1c2c4"

  cursor:
    text: CellBackground
    cursor: CellForeground

  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground

  search:
    matches:
      foreground: '#090b15'
      background: '#c1c2c4'
    focused_match:
      foreground: CellBackground
      background: CellForeground

  line_indicator:
    foreground: None
    background: None

  footer_bar:
    foreground: '#585b6c'
    background: '#c1c2c4'

  selection:
    text: CellBackground
    background: CellForeground

  normal:
    black: "#090b15"
    red: "#2F558E"
    green: "#35609F"
    yellow: "#355FA0"
    blue: "#3967AC"
    magenta: "#3B6BB3"
    cyan: "#3D6EBA"
    white: "#c1c2c4"

  bright:
    black: "#585b6c"
    red: "#2F558E"
    green: "#35609F"
    yellow: "#355FA0"
    blue: "#3967AC"
    magenta: "#3B6BB3"
    cyan: "#3D6EBA"
    white: "#c1c2c4"
