# Shell variables
# Generated by 'wal'
wallpaper="/data/data/com.termux/files/home/storage/dcim/Restored/IMG-20240726-WA0001.jpg"

# Special
background='#090b15'
foreground='#c1c2c4'
cursor='#c1c2c4'

# Colors
color0='#090b15'
color1='#2F558E'
color2='#35609F'
color3='#355FA0'
color4='#3967AC'
color5='#3B6BB3'
color6='#3D6EBA'
color7='#c1c2c4'
color8='#585b6c'
color9='#2F558E'
color10='#35609F'
color11='#355FA0'
color12='#3967AC'
color13='#3B6BB3'
color14='#3D6EBA'
color15='#c1c2c4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
