[colors]
background = '#090b158e'
black = '#090b15'
blue = '#2F558E'
cursor = '#c1c2c4'
cyan = '#35609F'
foreground = '#c1c2c4'
green = '#355FA0'
magenta = '#3967AC'
red = '#3B6BB3'
tabs = '#c1c2c4'
tabs-active = '#3D6EBA'
white = '#c1c2c4'
yellow = '#c1c2c4'
dim-black = '#090b158e'
dim-blue = '#2F558E8e'
dim-cyan = '#35609F8e'
dim-foreground = '#c1c2c48e'
dim-green = '#355FA08e'
dim-magenta = '#3967AC8e'
dim-red = '#3B6BB38e'
dim-white = '#3D6EBA8e'
dim-yellow = '#c1c2c48e'
light-black = '#2F558E'
light-blue = '#35609F'
light-cyan = '#355FA0'
light-foreground = '#3967AC'
light-green = '#3B6BB3'
light-magenta = '#3D6EBA'
light-red = '#c1c2c4'
light-white = '#2F558E'
light-yellow = '#35609F'
