#!/data/data/com.termux/files/usr/bin/bash

# Get the current volume of the "music" stream
#vol=$(termux-volume | jq '.[] | select(.stream == "music") | .volume')
#max=$(termux-volume | jq '.[] | select(.stream == "music") | .max_volume')

# Calculate simple percentage
#percent=$(( vol * 100 / max ))

# Choose Nerd Font icon based on the level
if [ "$percent" -eq 0 ]; then
    icon=" 󰝟" # Muted
elif [ "$percent" -lt 33 ]; then
    icon=" 󰕿" # Low
elif [ "$percent" -lt 66 ]; then
    icon=" 󰖀" # Mid
else
    icon=" 󰕾" # High
fi

echo "$icon $percent"
