#!/data/data/com.termux/files/usr/bin/bash

status=$(termux-wifi-connectioninfo | jq -r '.supplicant_state')

if [ "$status" == "COMPLETED" ]; then
    echo "󰖩"  # Connected icon
else
    echo "󰖪"  # Disconnected/error icon
fi

